### ISSUE TITLE
after upgrading raspian pipresents-next stops receiving gpio

### ISSUE THREAD

**Issue by najoshi** [KenT2/pipresents-next#33] opened 2015-11-10 06:58 UTC
Hi Ken, 

So I've been using pipresents-next for over a year now and I have made modifications to it for my digital photo frame project. Recently, because of problems I was having with omxplayer, I decided to update and upgrade the packages on my Raspian install. After I did this what happens is that after booting up and starting pipresents-next, after about 10 minutes, it ceases to respond to any gpio input. I tested the gpio with another script and it gets the signals just fine, but pipresents doesn't do anything... not with the buttons, switches, or the PIR. Do you have any idea what might cause that?
- Nik.

**Comment by KenT2** [comment] 2015-11-12 20:37
Hi
No ideas. I have had no other reports of this problem from other people. Because it happens after a while it might be worth checking its not a memory leak.

**Comment by najoshi** [comment] 2015-11-13 00:32
Doesn't python do automatic garbage collection? How would I even check for a memory leak? What is really strange is that before upgrading it worked (mostly) just fine... except that every once in a great while this gpio problem would happen and I would reboot and it was fine. But now, after upgrading but changing no code, it happens every time. Could it be because pipresents expects an older version of some package?

**Comment by KenT2** [comment] 2015-11-13 19:12
On 13/11/2015 00:32, najoshi wrote:
>
> Doesn't python do automatic garbage collection?
>
Not always, if your program has circular references.

> How would I even check for a memory leak?
>

look at the linux free command or there is a hidden widget on the task bar 
of Raspbian which will display memeory usage,
>
> What is really strange is that before upgrading it worked (mostly) just 
> fine... except that every once in a great while this gpio problem would 
> happen and I would reboot and it was fine. But now, after upgrading but 
> changing no code, it happens every time. Could it be because pipresents 
> expects an older version of some package?
>

Dunno, try free and see.

Ken

**Comment by najoshi** [comment] 2015-11-24 04:38
So it does seem like it's a memory issue, but the only changes I made to the code is flow control and signalling.... I'm not creating any objects or anything, so that shouldn't cause any memory leaks. However, what I forgot to mention is that I am using this as a photo frame for approximately 40,000 pictures and video. The size of the media.json file is ~32Mb, but still I feel like this shouldn't cause such a high memory usage.... pipresents-next is using ~300Mb of memory. Do you think this could be the issue, or is this more of an indication of a memory leak?

**Comment by KenT2** [comment] 2015-11-24 21:49
Here PP with pp_mediahow_1p3 is using about 50MB so 300MB seems rather large but could be caused by the .json file which is read and stored in RAM in a data structure. With your system running what is the % memory usage. I wonder if you might be getting disk thrashing which would slow down the PI considerably.

Does the memory usage increase with time and does it sharply reduce when PP is stopped including closing the terminal.

Are you using subshows which are called as part of a repeating mediashow. There is a memory leak in subshows  which I have been trying to find but it seems unlikely to cause a significant problem in 10 minutes.

You say you have been running PP for a while. Are you using a pre-Pi2 version of Raspbian. It would be worth getting the latest version of Raspbian Wheezy from the website and reinstalling your version of PP as updating an old version of Raspbian may have introduced problems.

**Comment by najoshi** [comment] 2015-11-25 12:23
I just upgraded to the Pi 2 and it does run now properly.... pipresents is using a steady 26% of (1GB) memory, regardless of whether it is paused or running. I am not using subshows, just a simple media show. I actually updated my Raspian before getting the Pi 2 and it caused pipresents to have memory problems every time I ran it, whereas before the upgrade it would only happen occasionally. Now, with the Pi 2, it works just fine, but it's only a temporary solution.... eventually I'm sure I'm going to run into the memory problem again since the usage increases with the number of pics and video in the media.json file.

**Comment by KenT2** [comment] 2015-11-25 12:35
I think we are talking about different types of memory. Mine was RAM yours was SD card. Anyway it sounds like your problem is solved for now so can the Issue be closed.

**Comment by najoshi** [comment] 2015-11-25 12:41
No, I am talking about RAM... It is using about 260Mb of RAM.... which is what it was using before I upgraded to the Pi 2.

**Comment by KenT2** [comment] 2015-11-25 13:02
Ah yes, sorry, misread your comment. I've just updated 5/5/2105 wheezy  to the latest version and run pp-gapless examples overnight without problems. I'll try pp-next as well.
It does sound like the problems are to do with the large number of files. PP isn't optimised for coping with large playlists as museums etc. would not be likely to have them.

**Closed** 2017-04-06 20:31 UTC
